-- Run this entire file in Supabase SQL Editor.
-- It creates the chat tables, profile creation trigger, security rules,
-- realtime publication, and the initial fyreakenspace admin profile.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username ~ '^[A-Za-z0-9_-]{2,24}$'),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  message text not null check (char_length(message) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key,
  admin_available boolean not null default false
);

insert into public.site_settings(id, admin_available)
values (1, false)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.site_settings enable row level security;

drop policy if exists "profiles readable by everyone" on public.profiles;
create policy "profiles readable by everyone"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "messages readable by everyone" on public.messages;
create policy "messages readable by everyone"
on public.messages for select
to anon, authenticated
using (true);

drop policy if exists "logged in users can send messages" on public.messages;
create policy "logged in users can send messages"
on public.messages for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "settings readable by everyone" on public.site_settings;
create policy "settings readable by everyone"
on public.site_settings for select
to anon, authenticated
using (true);

-- Only the admin profile may change the availability setting.
drop policy if exists "admin can update availability" on public.site_settings;
create policy "admin can update availability"
on public.site_settings for update
to authenticated
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
)
with check (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.is_admin = true
  )
);

-- Automatically create a profile from the username supplied during signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Realtime for messages and the availability setting.
do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.site_settings;
exception when duplicate_object then null;
end $$;

-- IMPORTANT:
-- After creating the fyreakenspace account through the website,
-- run the following command with its actual UUID:
--
-- update public.profiles
-- set is_admin = true
-- where username = 'fyreakenspace';
--
-- The website cannot safely make itself admin from the browser.

-- Optional cleanup if you need to remove a test account:
-- delete from auth.users where email = 'username@chat.local';